data01:
  - "true"
  - 3
  - 0
  - 1
  - 300
  - 500
  - 17
  - 33
  - "true"
  - "true"
  - 20000

data02:
  - 5
  - "true"
  - "I"
  - 1
  - 300
  - 500
  - 18
  - "true"
  - 37
  - "true"
  - 20000

data03:
  - 6
  - "false"
  - 7
  - 1
  - 2
  - 100
  - 200
  - 18
  - 35
  - "false"
  - "false"
  - 20000